import type { Docente } from './model';

export const MOCK_DOCENTES: Docente[] = [
  {
    id: '1',
    nombres: 'Rosa Elena',
    apellidos: 'Mamani Ccopa',
    dni: '11223344',
    correo: 'rmamani@ie70001.edu.pe',
    celular: '956123456',
    nivelEducativo: 'PRIMARIA',
    condicion: 'Nombrado',
    especialidad: 'Comunicación Integral',
    cargaHoraria: 30,
    secciones: [
      { id: 's1', grado: '4°', seccion: 'A' },
      { id: 's2', grado: '4°', seccion: 'B' },
    ],
    escala: 'IV',
    institucionId: '1',
    activo: true,
    fechaCreacion: '2023-03-01',
    cargo: 'Docente de Aula',
  },
  {
    id: '2',
    nombres: 'Jorge Luis',
    apellidos: 'Quispe Huanca',
    dni: '22334455',
    correo: 'jquispe@ie70001.edu.pe',
    celular: '957234567',
    nivelEducativo: 'PRIMARIA',
    condicion: 'Contratado',
    especialidad: 'Matemática',
    cargaHoraria: 24,
    secciones: [
      { id: 's3', grado: '5°', seccion: 'A' },
      { id: 's4', grado: '6°', seccion: 'A' },
    ],
    escala: 'II',
    institucionId: '1',
    activo: true,
    fechaCreacion: '2023-04-15',
    cargo: 'Docente de Aula',
  },
  {
    id: '3',
    nombres: 'María Fernanda',
    apellidos: 'Torres Condori',
    dni: '33445566',
    correo: 'mtorres@ie70001.edu.pe',
    celular: '958345678',
    nivelEducativo: 'PRIMARIA',
    condicion: 'Nombrado',
    especialidad: 'Ciencias Naturales',
    cargaHoraria: 28,
    secciones: [
      { id: 's5', grado: '3°', seccion: 'A' },
      { id: 's6', grado: '3°', seccion: 'B' },
      { id: 's7', grado: '2°', seccion: 'A' },
    ],
    escala: 'VI',
    institucionId: '1',
    activo: false,
    fechaCreacion: '2022-08-10',
    cargo: 'Docente de Aula',
  },
  {
    id: '4',
    nombres: 'Carlos Enrique',
    apellidos: 'Inca Flores',
    dni: '44556677',
    correo: 'cinca@ie70001.edu.pe',
    celular: '959456789',
    nivelEducativo: 'PRIMARIA',
    condicion: 'Contratado',
    especialidad: 'Educación Física',
    cargaHoraria: 20,
    secciones: [
      { id: 's8', grado: '1°', seccion: 'A' },
      { id: 's9', grado: '1°', seccion: 'B' },
    ],
    escala: 'I',
    institucionId: '1',
    activo: true,
    fechaCreacion: '2024-01-20',
    cargo: 'Docente de Aula',
  },
  {
    id: '5',
    nombres: 'Carlos',
    apellidos: 'Ruiz Condori',
    dni: '87654321',
    correo: 'carlos.ruiz@ie-huayta.edu.pe',
    celular: '951111222',
    nivelEducativo: 'SECUNDARIA',
    condicion: 'Asignado',
    especialidad: 'Gestión Escolar',
    cargaHoraria: 40,
    secciones: [],
    escala: 'VIII',
    institucionId: '8',
    activo: true,
    fechaCreacion: '2020-03-01',
    cargo: 'Director',
  },
  {
    id: '6',
    nombres: 'María',
    apellidos: 'Gómez Ticona',
    dni: '32145678',
    correo: 'maria.gomez@ugel-lampa.gob.pe',
    celular: '952222333',
    nivelEducativo: 'SECUNDARIA',
    condicion: 'Nombrado',
    especialidad: 'Acompañamiento Pedagógico',
    cargaHoraria: 40,
    secciones: [],
    escala: 'V',
    institucionId: '1',
    activo: true,
    fechaCreacion: '2021-03-01',
    cargo: 'Coordinador Pedagógico',
  },
  // ── Directores (cargo Director, 1 por IE, condición directiva, escala 1-8) ──
  {
    id: 'dir-1',
    nombres: 'Carlos Alberto',
    apellidos: 'Mendoza Ruiz',
    dni: '42895612',
    correo: 'cmendoza@ie71007.edu.pe',
    celular: '951110011',
    nivelEducativo: 'PRIMARIA',
    condicion: 'Asignado',
    especialidad: 'Gestión Escolar',
    cargaHoraria: 40,
    secciones: [],
    escala: 'V',
    institucionId: '1',
    activo: true,
    fechaCreacion: '2022-03-01',
    cargo: 'Director',
  },
  {
    id: 'dir-2',
    nombres: 'Elena Marina',
    apellidos: 'Torres Poma',
    dni: '09874521',
    correo: 'etorres@politecnico.edu.pe',
    celular: '952220022',
    nivelEducativo: 'SECUNDARIA',
    condicion: 'Encargado',
    especialidad: 'Gestión Escolar',
    cargaHoraria: 40,
    secciones: [],
    escala: 'III',
    institucionId: '2',
    activo: true,
    fechaCreacion: '2023-04-10',
    cargo: 'Director',
  },
  {
    id: 'dir-3',
    nombres: 'Javier Leonel',
    apellidos: 'Quispe Huamán',
    dni: '10563287',
    correo: 'jquispe@misprimerospasos.edu.pe',
    celular: '953330033',
    nivelEducativo: 'INICIAL',
    condicion: 'Asignado',
    especialidad: 'Gestión Escolar',
    cargaHoraria: 40,
    secciones: [],
    escala: 'IV',
    institucionId: '3',
    activo: true,
    fechaCreacion: '2021-08-15',
    cargo: 'Director',
  },
  {
    id: 'dir-4',
    nombres: 'Beatriz Lucía',
    apellidos: 'Salas Cárdenas',
    dni: '45698712',
    correo: 'bsalas@tupacamaru.edu.pe',
    celular: '954440044',
    nivelEducativo: 'SECUNDARIA',
    condicion: 'Encargado',
    especialidad: 'Gestión Escolar',
    cargaHoraria: 40,
    secciones: [],
    escala: 'VI',
    institucionId: '5',
    activo: true,
    fechaCreacion: '2020-03-20',
    cargo: 'Director',
  },
  {
    id: 'dir-5',
    nombres: 'Hilda Rosario',
    apellidos: 'Quispe Ticona',
    dni: '40112233',
    correo: 'hquispe@jcmariategui.edu.pe',
    celular: '955550055',
    nivelEducativo: 'PRIMARIA',
    condicion: 'Por función',
    especialidad: 'Gestión Escolar',
    cargaHoraria: 40,
    secciones: [],
    escala: 'II',
    institucionId: '4',
    activo: true,
    fechaCreacion: '2024-03-01',
    cargo: 'Director',
  },
  {
    id: 'dir-6',
    nombres: 'Néstor Iván',
    apellidos: 'Mamani Catacora',
    dni: '41556677',
    correo: 'nmamani@aacaceres.edu.pe',
    celular: '956660066',
    nivelEducativo: 'PRIMARIA',
    condicion: 'Asignado',
    especialidad: 'Gestión Escolar',
    cargaHoraria: 40,
    secciones: [],
    escala: 'VII',
    institucionId: '7',
    activo: false,
    fechaCreacion: '2019-05-12',
    cargo: 'Director',
  },
];
