import type { Especialista } from '../../entities/specialist/specialist.types';

export const MOCK_ESPECIALISTAS: Especialista[] = [
  {
    id: '1',
    nombres: 'Juan Carlos Pérez López',
    dni: '45678901',
    correo: 'jperez@ugel-lampa.gob.pe',
    celular: '951234567',
    especialidad: 'Matemática',
    rol: 'especialista_admin',
    niveles: ['Primaria', 'Secundaria'],
    activo: true,
    fechaCreacion: '2024-01-15',
  },
  {
    id: '2',
    nombres: 'María Elena Gómez Ticona',
    dni: '32145678',
    correo: 'mgomez@ugel-lampa.gob.pe',
    celular: '952345678',
    especialidad: 'Comunicación',
    rol: 'especialista_medio',
    niveles: ['Inicial', 'Primaria'],
    activo: true,
    fechaCreacion: '2024-02-10',
  },
  {
    id: '3',
    nombres: 'Pedro Huanca Flores',
    dni: '12345678',
    correo: 'phuanca@ugel-lampa.gob.pe',
    celular: '953456789',
    especialidad: 'Ciencias',
    rol: 'especialista_bajo',
    niveles: ['Secundaria'],
    activo: true,
    fechaCreacion: '2024-03-05',
  },
  {
    id: '4',
    nombres: 'Ana Rosa Torres Condori',
    dni: '65432198',
    correo: 'atorres@ugel-lampa.gob.pe',
    celular: '954567890',
    especialidad: 'Historia',
    rol: 'especialista_medio',
    niveles: ['Secundaria', 'EBA'],
    activo: false,
    fechaCreacion: '2024-03-20',
  },
  {
    id: '5',
    nombres: 'Roberto Inca Mamani',
    dni: '78901234',
    correo: 'rinca@ugel-lampa.gob.pe',
    celular: '955678901',
    especialidad: 'Educación Física',
    rol: 'especialista_bajo',
    niveles: ['Inicial', 'Primaria', 'Secundaria'],
    activo: true,
    fechaCreacion: '2024-04-01',
  },
];