import type { Cronograma } from './model';

export const MOCK_CRONOGRAMAS: Cronograma[] = [
  {
    id: '1',
    fechaHora: '2023-10-15T09:00',
    especialista: 'Juan Pérez',
    especialistaInitials: 'JP',
    institucion: 'IE 1023 Santa Rosa',
    docenteDirectivo: 'Ana Miranda Ortiz',
    tipo: 'DOCENTE',
    nroVisita: '02',
    estado: 'PROGRAMADO',
    modalidad: 'EBR',
    nivel: 'Inicial',
    observaciones: 'Revisión de carpetas pedagógicas y programación curricular del tercer trimestre.',
  },
  {
    id: '2',
    fechaHora: '2023-10-18T10:30',
    especialista: 'María García',
    especialistaInitials: 'MG',
    institucion: 'IE 4055 Libertador',
    docenteDirectivo: 'Roberto Sánchez',
    tipo: 'DIRECTIVO',
    nroVisita: '01',
    estado: 'EN PROCESO',
    modalidad: 'EBR',
    nivel: 'Primaria',
    observaciones: 'Monitoreo al Plan de Convivencia Escolar y planes de tutoría institucional.',
  },
  {
    id: '3',
    fechaHora: '2023-10-20T08:00',
    especialista: 'Carlos Mendoza',
    especialistaInitials: 'CM',
    institucion: 'IE 3022 Sagrado Corazón',
    docenteDirectivo: 'Luis Alberto Arce',
    tipo: 'DOCENTE',
    nroVisita: '03',
    estado: 'COMPLETADO',
    modalidad: 'EBR',
    nivel: 'Secundaria',
    observaciones: 'Evaluación del avance en el área de Ciencia y Tecnología. Uso de laboratorios.',
  },
  {
    id: '4',
    fechaHora: '2023-10-22T14:00',
    especialista: 'Ana Torres',
    especialistaInitials: 'AT',
    institucion: 'CEBA Túpac Amaru',
    docenteDirectivo: 'Carmen Rosa Díaz',
    tipo: 'DOCENTE',
    nroVisita: '01',
    estado: 'REPROGRAMADO',
    modalidad: 'EBA',
    nivel: 'Inicial-Intermedio',
    observaciones: 'Ajuste de cronograma por suspensión de actividades institucionales del CEBA.',
  },
  {
    id: '5',
    fechaHora: '2023-10-25T11:00',
    especialista: 'Juan Pérez',
    especialistaInitials: 'JP',
    institucion: 'IEI 70001 San Martín',
    docenteDirectivo: 'Sofía Ramos',
    tipo: 'DIRECTIVO',
    nroVisita: '02',
    estado: 'CANCELADO',
    modalidad: 'EBR',
    nivel: 'Inicial',
    observaciones: 'Cruzado con capacitación nacional convocada por el MINEDU.',
  },
  {
    id: '6',
    fechaHora: '2023-10-28T08:30',
    especialista: 'María García',
    especialistaInitials: 'MG',
    institucion: 'IE 5011 Fe y Alegría',
    docenteDirectivo: 'Pedro Infante',
    tipo: 'DOCENTE',
    nroVisita: '01',
    estado: 'PROGRAMADO',
    modalidad: 'EBR',
    nivel: 'Primaria',
    observaciones: 'Revisión del portafolio del docente y sesión de aprendizaje interactiva de matemáticas.',
  },
  {
    id: '7',
    fechaHora: '2023-11-02T15:00',
    especialista: 'Rosa Quispe',
    especialistaInitials: 'RQ',
    institucion: 'CEBE San Juan de Dios',
    docenteDirectivo: 'Juana de Arco',
    tipo: 'DIRECTIVO',
    nroVisita: '04',
    estado: 'PROGRAMADO',
    modalidad: 'EBE',
    nivel: 'CEBE',
    observaciones: 'Monitoreo administrativo y revisión de protocolos de seguridad inclusiva.',
  },
  {
    id: '8',
    fechaHora: '2023-11-05T09:30',
    especialista: 'Carlos Mendoza',
    especialistaInitials: 'CM',
    institucion: 'IE 3022 Sagrado Corazón',
    docenteDirectivo: 'Julio César',
    tipo: 'DOCENTE',
    nroVisita: '02',
    estado: 'EN PROCESO',
    modalidad: 'EBR',
    nivel: 'Secundaria',
    observaciones: 'Acompañamiento en aula a docente de Ciencias Sociales sobre competencias ciudadanas.',
  },
  {
    id: '9',
    fechaHora: '2023-11-10T10:00',
    especialista: 'Juan Pérez',
    especialistaInitials: 'JP',
    institucion: 'IE 1023 Santa Rosa',
    docenteDirectivo: 'Marco Aurelio',
    tipo: 'DOCENTE',
    nroVisita: '01',
    estado: 'COMPLETADO',
    modalidad: 'EBR',
    nivel: 'Inicial',
    observaciones: 'Monitoreo de rutinas diarias y material lúdico utilizado en el nivel inicial.',
  },
  {
    id: '10',
    fechaHora: '2023-11-12T13:00',
    especialista: 'Pedro Alvarado',
    especialistaInitials: 'PA',
    institucion: 'CEBA José Carlos Mariátegui',
    docenteDirectivo: 'Cleopatra Mendoza',
    tipo: 'DIRECTIVO',
    nroVisita: '03',
    estado: 'PROGRAMADO',
    modalidad: 'EBA',
    nivel: 'Avanzado',
    observaciones: 'Monitoreo al director sobre el avance de metas físicas del Plan Anual de Trabajo.',
  },
  {
    id: '11',
    fechaHora: '2023-11-15T08:00',
    especialista: 'María García',
    especialistaInitials: 'MG',
    institucion: 'IE 4055 Libertador',
    docenteDirectivo: 'Simón Bolívar',
    tipo: 'DOCENTE',
    nroVisita: '02',
    estado: 'REPROGRAMADO',
    modalidad: 'EBR',
    nivel: 'Primaria',
    observaciones: 'Reprogramado por huelga local. Nueva fecha establecida de mutuo acuerdo.',
  },
  {
    id: '12',
    fechaHora: '2023-11-18T16:00',
    especialista: 'Luis Mamani',
    especialistaInitials: 'LM',
    institucion: 'PRITE Virgen de la Candelaria',
    docenteDirectivo: 'José de San Martín',
    tipo: 'DIRECTIVO',
    nroVisita: '01',
    estado: 'COMPLETADO',
    modalidad: 'EBE',
    nivel: 'PRITE',
    observaciones: 'Visita de monitoreo a la gestión de atención temprana infantil.',
  },
  {
    id: '13',
    fechaHora: '2023-10-12T08:30',
    especialista: 'Klisman Condori',
    especialistaInitials: 'KC',
    institucion: 'I.E. 70005 - Lampa Central',
    docenteDirectivo: 'Prof. Ana Martínez',
    tipo: 'DOCENTE',
    nroVisita: '02',
    estado: 'EN PROCESO',
    modalidad: 'EBR',
    nivel: 'Primaria',
    observaciones: 'Revisión de planillas de evaluación del segundo trimestre. Traer formatos A-4 actualizados.',
  },
  {
    id: '14',
    fechaHora: '2023-10-12T11:00',
    especialista: 'Jean Carlos Choque',
    especialistaInitials: 'JC',
    institucion: 'I.E. 70005 - Lampa Central',
    docenteDirectivo: 'Director Luis Quiroga',
    tipo: 'DIRECTIVO',
    nroVisita: '01',
    estado: 'PROGRAMADO',
    modalidad: 'EBR',
    nivel: 'Primaria',
    observaciones: 'Supervisión de infraestructura escolar e inventario de material tecnológico.',
  },
  {
    id: '15',
    fechaHora: '2023-10-12T14:30',
    especialista: 'María García',
    especialistaInitials: 'MG',
    institucion: 'IE 5011 Fe y Alegría',
    docenteDirectivo: 'Prof. Pedro Ramos',
    tipo: 'DOCENTE',
    nroVisita: '03',
    estado: 'PROGRAMADO',
    modalidad: 'EBR',
    nivel: 'Primaria',
    observaciones: 'Revisión del avance curricular en comprensión lectora.',
  },
  {
    id: '16',
    fechaHora: '2023-10-12T16:00',
    especialista: 'Carlos Mendoza',
    especialistaInitials: 'CM',
    institucion: 'IE 3022 Sagrado Corazón',
    docenteDirectivo: 'Prof. Diana Gómez',
    tipo: 'DOCENTE',
    nroVisita: '02',
    estado: 'COMPLETADO',
    modalidad: 'EBR',
    nivel: 'Secundaria',
    observaciones: 'Evaluación del proyecto feria de ciencias local.',
  },
  {
    id: '17',
    fechaHora: '2023-10-05T09:00',
    especialista: 'Pedro Alvarado',
    especialistaInitials: 'PA',
    institucion: 'CETPRO Industrial Puno',
    docenteDirectivo: 'Prof. Juan Ramos',
    tipo: 'DOCENTE',
    nroVisita: '01',
    estado: 'COMPLETADO',
    modalidad: 'CEPTRO',
    nivel: 'Corte y Ensamblaje',
    observaciones: 'Monitoreo técnico en el taller de soldadura e indumentaria de seguridad.',
  },
  {
    id: '18',
    fechaHora: '2023-10-02T10:00',
    especialista: 'Juan Pérez',
    especialistaInitials: 'JP',
    institucion: 'IE 1023 Santa Rosa',
    docenteDirectivo: 'Directora Juana Luna',
    tipo: 'DIRECTIVO',
    nroVisita: '01',
    estado: 'PROGRAMADO',
    modalidad: 'EBR',
    nivel: 'Inicial',
    observaciones: 'Acompañamiento a la dirección en el proceso de matrícula escolar del período complementario.',
  },
  {
    id: '19',
    fechaHora: '2023-12-05T09:00',
    especialista: 'Juan Pérez',
    especialistaInitials: 'JP',
    institucion: 'IE 1023 Santa Rosa',
    docenteDirectivo: 'Prof. Ana Miranda Ortiz',
    tipo: 'DOCENTE',
    nroVisita: '03',
    estado: 'PROGRAMADO',
    modalidad: 'EBR',
    nivel: 'Inicial',
    observaciones: 'Monitoreo a futuro: Evaluación final de logros de aprendizaje y cierre del año escolar.',
  },
  {
    id: '20',
    fechaHora: '2023-12-12T10:30',
    especialista: 'María García',
    especialistaInitials: 'MG',
    institucion: 'IE 4055 Libertador',
    docenteDirectivo: 'Roberto Sánchez',
    tipo: 'DIRECTIVO',
    nroVisita: '02',
    estado: 'PROGRAMADO',
    modalidad: 'EBR',
    nivel: 'Primaria',
    observaciones: 'Monitoreo a futuro: Planificación curricular del próximo año y gestión de matrícula.',
  },
  {
    id: '21',
    fechaHora: '2023-12-20T08:30',
    especialista: 'Carlos Mendoza',
    especialistaInitials: 'CM',
    institucion: 'IE 3022 Sagrado Corazón',
    docenteDirectivo: 'Luis Alberto Arce',
    tipo: 'DOCENTE',
    nroVisita: '04',
    estado: 'PROGRAMADO',
    modalidad: 'EBR',
    nivel: 'Secundaria',
    observaciones: 'Monitoreo a futuro: Entrega de libretas de calificaciones y balances pedagógicos.',
  },
  {
    id: '22',
    fechaHora: '2023-11-24T14:30',
    especialista: 'Ana Torres',
    especialistaInitials: 'AT',
    institucion: 'CEBA Túpac Amaru',
    docenteDirectivo: 'Carmen Rosa Díaz',
    tipo: 'DOCENTE',
    nroVisita: '02',
    estado: 'PROGRAMADO',
    modalidad: 'EBA',
    nivel: 'Inicial-Intermedio',
    observaciones: 'Monitoreo a futuro: Visita de verificación de portafolios del cuarto bimestre.',
  }
];
