import type { Especialista } from './model';

export const MOCK_ESPECIALISTAS: Especialista[] = [
  {
    id: '1',
    personaId: 'p1',
    nombres: 'Juan Carlos',
    apellidos: 'Pérez López',
    dni: '45678901',
    correo: 'jperez@ugel-lampa.gob.pe',
    celular: '951234567',
    especialidad: 'Matemática',
    nivelEducativo: 'Secundaria',
    modalidad: 'EBR',
    estado: 'Activo',
    activo: true,
    fechaCreacion: '2024-01-15',
    condicionLaboral: 'Nombrado',
    cargaLaboral: 40,
    cargo: 'Especialista',
    rolCode: 'especialista',
  },
  {
    id: '2',
    personaId: 'p2',
    nombres: 'María Elena',
    apellidos: 'Gómez Ticona',
    dni: '32145678',
    correo: 'mgomez@ugel-lampa.gob.pe',
    celular: '952345678',
    especialidad: 'Comunicación',
    nivelEducativo: 'Primaria',
    modalidad: 'EBR',
    estado: 'Activo',
    activo: true,
    fechaCreacion: '2024-02-10',
    condicionLaboral: 'Encargado',
    cargaLaboral: 40,
    cargo: 'Especialista',
    rolCode: 'especialista',
  },
  {
    id: '3',
    personaId: 'p3',
    nombres: 'Pedro',
    apellidos: 'Huanca Flores',
    dni: '12345678',
    correo: 'phuanca@ugel-lampa.gob.pe',
    celular: '953456789',
    cargaLaboral: 40,
    nivelEducativo: 'Secundaria',
    modalidad: 'EBR',
    estado: 'Activo',
    activo: true,
    fechaCreacion: '2024-03-05',
    condicionLaboral: 'Nombrado',
    cargo: 'Jefe de Área',
    rolCode: 'jefe_area',
  },
  {
    id: '4',
    personaId: 'p4',
    nombres: 'Ana Rosa',
    apellidos: 'Torres Condori',
    dni: '65432198',
    correo: 'atorres@ugel-lampa.gob.pe',
    celular: '954567890',
    especialidad: 'Historia',
    nivelEducativo: 'Secundaria',
    modalidad: 'EBR',
    estado: 'Inactivo',
    activo: false,
    fechaCreacion: '2024-03-20',
    condicionLaboral: 'Designado',
    cargaLaboral: 40,
    cargo: 'Especialista',
    rolCode: 'especialista',
  },
  {
    id: '5',
    personaId: 'p5',
    nombres: 'Roberto',
    apellidos: 'Inca Mamani',
    dni: '78901234',
    correo: 'rinca@ugel-lampa.gob.pe',
    celular: '955678901',
    cargaLaboral: 30,
    nivelEducativo: 'Inicial',
    modalidad: 'EBR',
    estado: 'Activo',
    activo: true,
    fechaCreacion: '2024-04-01',
    condicionLaboral: 'Nombrado',
    cargo: 'Jefe de Área',
    rolCode: 'jefe_area',
  },
];
