import type { Docente } from './teacher.types';

export const MOCK_DOCENTES: Docente[] = [
  {
    id: '1',
    nombres:        'Rosa Elena Mamani Ccopa',
    dni:            '11223344',
    correo:         'rmamani@ie70001.edu.pe',
    celular:        '956123456',
    nivelEducativo: 'Primaria',
    condicion:      'Nombrado',
    especialidad:   'Comunicación Integral',
    cargaHoraria:   30,
    secciones:      [
      { id: 's1', grado: '4to A' },
      { id: 's2', grado: '4to B' },
    ],
    escala:         'IV',
    institucionId:  '1',
    activo:         true,
    fechaCreacion:  '2023-03-01',
    cargo:          'Docente de Aula',
  },
  {
    id: '2',
    nombres:        'Jorge Luis Quispe Huanca',
    dni:            '22334455',
    correo:         'jquispe@ie70001.edu.pe',
    celular:        '957234567',
    nivelEducativo: 'Primaria',
    condicion:      'Contratado',
    especialidad:   'Matemática',
    cargaHoraria:   24,
    secciones:      [
      { id: 's3', grado: '5to A' },
      { id: 's4', grado: '6to A' },
    ],
    escala:         'II',
    institucionId:  '1',
    activo:         true,
    fechaCreacion:  '2023-04-15',
    cargo:          'Docente de Aula',
  },
  {
    id: '3',
    nombres:        'María Fernanda Torres Condori',
    dni:            '33445566',
    correo:         'mtorres@ie70001.edu.pe',
    celular:        '958345678',
    nivelEducativo: 'Primaria',
    condicion:      'Nombrado',
    especialidad:   'Ciencias Naturales',
    cargaHoraria:   28,
    secciones:      [
      { id: 's5', grado: '3ro A' },
      { id: 's6', grado: '3ro B' },
      { id: 's7', grado: '2do A' },
    ],
    escala:         'VI',
    institucionId:  '1',
    activo:         false,
    fechaCreacion:  '2022-08-10',
    cargo:          'Docente de Aula',
  },
  {
    id: '4',
    nombres:        'Carlos Enrique Inca Flores',
    dni:            '44556677',
    correo:         'cinca@ie70001.edu.pe',
    celular:        '959456789',
    nivelEducativo: 'Primaria',
    condicion:      'Contratado',
    especialidad:   'Educación Física',
    cargaHoraria:   20,
    secciones:      [
      { id: 's8', grado: '1ro A' },
      { id: 's9', grado: '1ro B' },
    ],
    escala:         'I',
    institucionId:  '1',
    activo:         true,
    fechaCreacion:  '2024-01-20',
    cargo:          'Docente de Aula',
  },
  {
    id: '5',
    nombres:        'Carlos Ruiz Condori',
    dni:            '87654321',
    correo:         'carlos.ruiz@ie-huayta.edu.pe',
    celular:        '951111222',
    nivelEducativo: 'Secundaria',
    condicion:      'Nombrado',
    especialidad:   'Gestión Escolar',
    cargaHoraria:   40,
    secciones:      [],
    escala:         'VIII',
    institucionId:  '1',
    activo:         true,
    fechaCreacion:  '2020-03-01',
    cargo:          'Director',
  },
  {
    id: '6',
    nombres:        'María Gómez Ticona',
    dni:            '32145678',
    correo:         'maria.gomez@ugel-lampa.gob.pe',
    celular:        '952222333',
    nivelEducativo: 'Secundaria',
    condicion:      'Nombrado',
    especialidad:   'Acompañamiento Pedagógico',
    cargaHoraria:   40,
    secciones:      [],
    escala:         'V',
    institucionId:  '1',
    activo:         true,
    fechaCreacion:  '2021-03-01',
    cargo:          'Coordinador Pedagógico',
  },
];